In [2]:
import pandas as pd
import numpy as np

##### Cargar la data de salarios

In [3]:
data = pd.read_csv('../Datasets casos de estudio 2/Case study 1/cs2.1.csv')

##### Variables en dataset


In [4]:
data.head()

female  cg  sc  hsg  mw  so  we  ne  exp1   exp2    exp3       wage
0       0   0   0    1   0   0   0   1  33.0  10.89  35.937  11.659091
1       0   1   0    0   0   0   0   1  27.0   7.29  19.683  12.825000
2       0   0   1    0   0   0   0   1  13.0   1.69   2.197   5.777027
3       0   1   0    0   0   0   0   1   2.0   0.04   0.008  12.468750
4       1   1   0    0   0   0   0   1  15.0   2.25   3.375  18.525000

In [8]:
data.dtypes

female      int64
cg          int64
sc          int64
hsg         int64
mw          int64
so          int64
we          int64
ne          int64
exp1      float64
exp2      float64
exp3      float64
wage      float64
dtype: object

##### Dimensiones del dataset

In [9]:
data.shape

(3835, 12)

##### Estadisticos principales

In [10]:
data.describe()

female           cg           sc         hsg           mw  \
count  3835.000000  3835.000000  3835.000000  3835.00000  3835.000000   
mean      0.417992     0.376271     0.323859     0.29987     0.287614   
std       0.493293     0.484513     0.468008     0.45826     0.452709   
min       0.000000     0.000000     0.000000     0.00000     0.000000   
25%       0.000000     0.000000     0.000000     0.00000     0.000000   
50%       0.000000     0.000000     0.000000     0.00000     0.000000   
75%       1.000000     1.000000     1.000000     1.00000     1.000000   
max       1.000000     1.000000     1.000000     1.00000     1.000000   

                so           we           ne         exp1         exp2  \
count  3835.000000  3835.000000  3835.000000  3835.000000  3835.000000   
mean      0.243546     0.211734     0.257106    13.353194     2.529267   
std       0.429278     0.408591     0.437095     8.639348     2.910554   
min       0.000000     0.000000     0.000000     2.000000     0.040000   
25%       0.000000     0.000000     0.000000     6.000000     0.360000   
50%       0.000000     0.000000     0.000000    11.000000     1.210000   
75%       0.000000     0.000000     1.000000    19.500000     3.802500   
max       1.000000     1.000000     1.000000    35.000000    12.250000   

              exp3         wage  
count  3835.000000  3835.000000  
mean      5.812103    15.533356  
std       9.033207    13.518165  
min       0.008000     0.004275  
25%       0.216000     9.618750  
50%       1.331000    13.028571  
75%       7.414875    17.812500  
max      42.875000   348.333017

##### Linear Regression para el salario

In [11]:
data = data.rename(columns={'wage': 'salario'})

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [13]:
lr = LinearRegression()

In [16]:
X = data.iloc[:,:11]
Y = data.iloc[:,11]

In [17]:
X.head()

female  cg  sc  hsg  mw  so  we  ne  exp1   exp2    exp3
0       0   0   0    1   0   0   0   1  33.0  10.89  35.937
1       0   1   0    0   0   0   0   1  27.0   7.29  19.683
2       0   0   1    0   0   0   0   1  13.0   1.69   2.197
3       0   1   0    0   0   0   0   1   2.0   0.04   0.008
4       1   1   0    0   0   0   0   1  15.0   2.25   3.375

In [18]:
Y.head()

0    11.659091
1    12.825000
2     5.777027
3    12.468750
4    18.525000
Name: salario, dtype: float64

##### Run Linear Specification and compute MSE and R^2

In [19]:
full_fit = lr.fit(X, Y)

In [27]:
y_predict = lr.predict(X)

In [118]:
p_fmla1 = X.shape
p_fmla1 = p_fmla1[1]
p_fmla1

9

In [32]:
#Crear formula para obtener R2
def adj_r2_score(model,y,yhat):
        adj = 1 - float(len(y)-1)/(len(y)-len(model.coef_)-1)*(1 - metrics.r2_score(y,yhat))
        return adj
    

##### R2 y R2 ajustado

In [93]:
# R2 
r2_fmla1 = lr.score(X,Y)
r2_fmla1

0.09548800312274774

In [94]:
# R2_adjusted
r2_adj_fmla1 = adj_r2_score(lr,Y,y_predict)
r2_adj_fmla1

0.09288543132948324

##### MSE

In [95]:
# MSE
mse_fmla1 = mean_squared_error(Y, y_predict)
mse_fmla1

165.2481339759127

### Creacion de nuevas variables cuadraticas

In [124]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(2, interaction_only=True)

In [97]:
X = X.drop(['mw','ne'], axis = 1)
X.head()

female  cg  sc  hsg  so  we  exp1   exp2    exp3
0       0   0   0    1   0   0  33.0  10.89  35.937
1       0   1   0    0   0   0  27.0   7.29  19.683
2       0   0   1    0   0   0  13.0   1.69   2.197
3       0   1   0    0   0   0   2.0   0.04   0.008
4       1   1   0    0   0   0  15.0   2.25   3.375

In [98]:
interac_var = X.iloc[:,1:]
interac_var.head()

cg  sc  hsg  so  we  exp1   exp2    exp3
0   0   0    1   0   0  33.0  10.89  35.937
1   1   0    0   0   0  27.0   7.29  19.683
2   0   1    0   0   0  13.0   1.69   2.197
3   1   0    0   0   0   2.0   0.04   0.008
4   1   0    0   0   0  15.0   2.25   3.375

In [99]:
female = np.array(X.iloc[:,0])
female

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [125]:
new_features = pf.fit_transform(interac_var)
new_features

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 3.5937000e+02,
        1.1859210e+03, 3.9135393e+02],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.9683000e+02,
        5.3144100e+02, 1.4348907e+02],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 2.1970000e+01,
        2.8561000e+01, 3.7129300e+00],
       ...,
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 5.8320000e+01,
        1.0497600e+02, 1.8895680e+01],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.2500000e+00,
        6.2500000e-01, 3.1250000e-02],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.9683000e+02,
        5.3144100e+02, 1.4348907e+02]])

In [126]:
print('female: {}'.format(female.shape))
print('new_features: {}'.format(new_features.shape))

female: (3835,)
new_features: (3835, 37)


In [127]:
X_poly = np.append(female.reshape(-1,1),new_features, axis = 1)
X_poly.shape

(3835, 38)

In [128]:
interac_var2 = X.iloc[:,1:3]
interac_var2.head()

cg  sc
0   0   0
1   1   0
2   0   1
3   1   0
4   1   0

In [129]:
new_features2 = pf.fit_transform(interac_var2)
new_features2

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       ...,
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [130]:
X_poly_2var = np.append(female.reshape(-1,1),new_features2, axis = 1)
X_poly_2var.shape

(3835, 5)

##### Run Quadratic specification and compute MSE an R^2

In [131]:
fmla2 = lr.fit(X_poly, Y)
p_fmla2 = X_poly.shape
p_fmla2 = p_fmla2[1]
y_predict_fmla2 = lr.predict(X_poly)
# R2 
r2_fmla2 = lr.score(X_poly,Y)
# R2_adjusted
r2_adj_fmla2 = adj_r2_score(lr,Y,y_predict_fmla2)
# MSE 
mse_fmla2 = mean_squared_error(Y,y_predict_fmla2)

In [132]:
p_fmla2

38

##### Resumen de los calculos

In [136]:
table = np.ndarray((2,4))
table[0,] = (p_fmla1, r2_fmla1, r2_adj_fmla1, mse_fmla1)
table[1,] = (p_fmla2, r2_fmla2, r2_adj_fmla2, mse_fmla2)
table = pd.DataFrame(table, columns=['p','R2','R2_adj','MSE'], index=['Basic reg','Flexible reg'])
table

p        R2    R2_adj         MSE
Basic reg      9.0  0.095488  0.092885  165.248134
Flexible reg  38.0  0.101494  0.092500  164.150812

In [134]:
##### Linear and Quadratic specifications with Sample Splitting

In [135]:
from sklearn.model_selection import train_test_split

##### Basic reg & Flexbile split

In [137]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 42, shuffle = True)
x_train_poly, x_test_poly, y_train_poly, y_test_poly = train_test_split(X_poly, Y, test_size = 0.25, random_state = 42, shuffle = True)


##### Basic

In [142]:
fmla1 = lr.fit(x_train, y_train)
p_fmla1 = x_train.shape
p_fmla1 = p_fmla1[1]
y_pred_test = lr.predict(x_test)
y_pred_train = lr.predict(x_train)

print('Calculo de scores para training')
# R2 
r2_fmla1_train = lr.score(x_train,y_train)
print('R^2:{}'.format(r2_fmla1_train))
# R2_adjusted
r2_adj_fmla1_train = adj_r2_score(lr, y_train, y_pred_train)
print('R^2_adj:{}'.format(r2_adj_fmla1_train))
# MSE 
mse_fmla1_train = mean_squared_error(y_train, y_pred_train)
print('MSE:{}'.format(mse_fmla1_train))

print('Calculo de scores para test')
# R2 
r2_fmla1_test = lr.score(x_test,y_test)
print('R^2:{}'.format(r2_fmla1_test))
# R2_adjusted
r2_adj_fmla1_test = adj_r2_score(lr, y_test, y_pred_test)
print('R^2_adj:{}'.format(r2_adj_fmla1_test))
# MSE 
mse_fmla1_test = mean_squared_error(y_test, y_pred_test)
print('MSE:{}'.format(mse_fmla1_test))

Calculo de scores para training
R^2:0.0957172775763746
R^2_adj:0.09287759003212726
MSE:159.23581245038653
Calculo de scores para test
R^2:0.08896184704009168
R^2_adj:0.08032186455680479
MSE:184.47564883513414


##### Flexible

In [146]:
fmla1 = lr.fit(x_train_poly, y_train_poly)
p_fmla1_poly = x_train_poly.shape
p_fmla1_poly = p_fmla1_poly[1]
y_pred_test_poly = lr.predict(x_test_poly)
y_pred_train_poly = lr.predict(x_train_poly)

print('Calculo de scores para training')
# R2 
r2_fmla1_train_poly = lr.score(x_train_poly,y_train_poly)
print('R^2:{}'.format(r2_fmla1_train_poly))
# R2_adjusted
r2_adj_fmla1_train_poly = adj_r2_score(lr, y_train_poly, y_pred_train)
print('R^2_adj:{}'.format(r2_adj_fmla1_train_poly))
# MSE 
mse_fmla1_train_poly = mean_squared_error(y_train_poly, y_pred_train_poly)
print('MSE:{}'.format(mse_fmla1_train_poly))

print('Calculo de scores para test')
# R2 
r2_fmla1_test_poly = lr.score(x_test_poly,y_test_poly)
print('R^2:{}'.format(r2_fmla1_test_poly))
# R2_adjusted
r2_adj_fmla1_test_poly = adj_r2_score(lr, y_test_poly, y_pred_test_poly)
print('R^2_adj:{}'.format(r2_adj_fmla1_test_poly))
# MSE 
mse_fmla1_test_poly = mean_squared_error(y_test_poly, y_pred_test_poly)
print('MSE:{}'.format(mse_fmla1_test_poly))

Calculo de scores para training
R^2:0.10079725810843665
R^2_adj:0.08360492528448249
MSE:158.3412749266716
Calculo de scores para test
R^2:0.09876123070193364
R^2_adj:0.06153615110049171
MSE:182.49137665802562


In [147]:
table = np.ndarray((4,4))
table[0,] = (p_fmla1, r2_fmla1_train, r2_adj_fmla1_train, mse_fmla1_train)
table[1,] = (p_fmla1, r2_fmla1_test, r2_adj_fmla1_test, mse_fmla1_test)
table[2,] = (p_fmla1_poly, r2_fmla1_train_poly, r2_adj_fmla1_train_poly, mse_fmla1_train_poly)
table[3,] = (p_fmla1_poly, r2_fmla1_test_poly, r2_adj_fmla1_test_poly, mse_fmla1_test_poly)

table = pd.DataFrame(table, columns=['p','R2','R2_adj','MSE'], index=['Basic reg train','Basic reg test',
                                                                      'Flexible reg train','Flexible reg test'])
table

p        R2    R2_adj         MSE
Basic reg train      9.0  0.095717  0.092878  159.235812
Basic reg test       9.0  0.088962  0.080322  184.475649
Flexible reg train  38.0  0.100797  0.083605  158.341275
Flexible reg test   38.0  0.098761  0.061536  182.491377